### ISSUE TITLE
[question only] blink compat

### ISSUE THREAD

**Issue by cotko** [Saghen/blink.compat#10]
Hey,

Is it possible to get [cmp-cmdline](https://github.com/hrsh7th/cmp-cmdline) to work with blink compat?
I don't exactly know how to register ":" and "/" to trigger completions from that source.

**Comment by stefanboca** [comment]
Command line completion is currently not supported in either blink.compat or blink.cmp, but is planned to be a native feature in blink.cmp - see the [README](https://github.com/Saghen/blink.cmp?tab=readme-ov-file#planned-missing-features)
