### ISSUE TITLE
Keep asking for `impersonate_nvim_cmp`

### ISSUE THREAD

**Issue by DrummyFloyd** [Saghen/blink.compat#17]
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp` and `blink.compat`
- [X] I have read the README

### Bug Description

any idea why `blink.compat` can't work with this ? 
 ```log
                       blink.compat completion source "emoji" has not registered itself.
 Please try enabling `impersonate_nvim_cmp` in blink.compat `opts`
```

### Relevant configuration

```lua
return {
  {
    "saghen/blink.cmp",
    opts_extend = { "sources.completion.enabled_providers", "sources.compat" },
    dependencies = {
      { "allaman/emoji.nvim" },
      {
        "saghen/blink.compat",
        opts = { impersonate_nvim_cmp = true, enable_events = true, debug = true },
      },
    },
    opts = {
      sources = {
        completion = {
          enabled_providers = { "emoji" },
        },
        compat = { "emoji" },
        providers = {
          emoji = {
            name = "emoji",
            module = "blink.compat.source",
            opts = { enable_cmp_integration = true },
          },
        },
      },
    },
  },
}
```

### neovim version

NVIM v0.10.2 Build type: Release LuaJIT 2.1.1713484068 Run "nvim -V1 -v" for more info

### `blink.cmp` version: branch, tag, or commit

0.7.2

### `blink.compat` version: branch, tag, or commit

2.1.2

**Comment by stefanboca** [comment]
Here's a config I got to work:
```lua
return {
  {
    "allaman/emoji.nvim",
    opts = { enable_cmp_integration = true },
  },
  {
    "saghen/blink.compat",
    lazy = true,
    opts = {},
  },
  {
    "saghen/blink.cmp",
    dependencies = {},
    opts = {
      sources = {
        completion = {
          enabled_providers = { "emoji" },
        },
        providers = {
          emoji = {
            name = "emoji",
            module = "blink.compat.source",
          },
        },
      },
    },
  },
}
```

The main issue here is that the `opts` in the providers is **NOT** the same as the `opts` of the plugin spec. `lazy.nvim` only calls a plugin's `setup` if `opts` or `config` is set in their spec, so in your config above, `emoji.nvim` wasn't getting setup and registering itself with cmp. I'll clarify the readme.

**Comment by DrummyFloyd** [comment]
thank you for your explanations!

**Comment by stefanboca** [comment]
@DrummyFloyd I forgot to mention, but `opts.sources.compat` is specifically a field added by LazyVim that just helps remove the boilerplate of adding new compat sources. It just rewrites eg
```lua
sources = {
  compat = { "<source>" }
}
```
into
```lua
sources = {
  completion = { enabled_providers = { "<source>" } },
  providers = {
    ["<source>"] = {
      name = "<source>",
      module = "blink.compat.source",
    }
  }
}
```
for each element of `sources.compat`. You can certainly use it in your config if you're using LazyVim, but the field is not something that blink uses.
