### ISSUE TITLE
Crashes when using Codeium source

### ISSUE THREAD

**Issue by elu00** [Saghen/blink.compat#3]
Hi,

Thanks for the plugin. I'm currently trying to get [this codeium source](https://github.com/Exafunction/codeium.nvim) working through the compatibility layer, but am having various issues installing/getting everything configured. I think I've narrowed the issue down to [this line,](https://github.com/Exafunction/codeium.nvim/blob/dddaee0d1e9a1d0bcaea66f08a8103b3cdf26604/lua/codeium/source.lua#L97) which tries to call a part of the cmp api that isn't mirrored yet in blink. Commenting out lines 97-112 of this file locally lets me get codeium installed, but then completions through blink seem not to work, although the virtual text provided by the plugin does.
Any chance the extra event related stuff could get implemented here?

Here's the relevant part of my config:

```	
       {
		"hrsh7th/nvim-cmp",
		enabled = false,
	},
	{
		"saghen/blink.cmp",
		dependencies = {
			-- add blink.compat to dependencies
			{ "saghen/blink.compat", opts = { impersonate_nvim_cmp = true } },
			{
				"Exafunction/codeium.nvim",
				cmd = "Codeium",
				build = ":Codeium Auth",
				opts = { virtual_text = { enabled = true } },
			},
		},
		event = "BufReadPre",
		version = "v0.*", -- REQUIRED release tag to download pre-built binaries
		-- https://github.com/chrisgrieser/.config/blob/main/nvim/lua/plugins/blink-cmp.lua

		---@module "blink.cmp"
		---@type blink.cmp.Config
		opts = {
			sources = {
				completion = {
					enabled_providers = { "lsp", "path", "snippets", "buffer", "codeium" },
				},
				providers = {
					codeium = {
						name = "codeium", -- IMPORTANT: use the same name as you would for nvim-cmp
						module = "blink.compat.source",

						-- all blink.cmp source config options work as normal:
						--score_offset = -3,

						opts = {
							-- options passed to the completion source
							-- equivalent to `option` field of nvim-cmp source config

							cache_digraphs_on_start = true,
						},
					},

					lsp = {
						name = "LSP",
						module = "blink.cmp.sources.lsp",

					},
					path = {
						name = "Path",
						module = "blink.cmp.sources.path",
						score_offset = 3,
						opts = {
							trailing_slash = false,
							label_trailing_slash = true,
							get_cwd = function(context)
								return vim.fn.expand(("#%d:p:h"):format(context.bufnr))
							end,
							show_hidden_files_by_default = false,
						},
					},
					snippets = {
						name = "Snippets",
						module = "blink.cmp.sources.snippets",
						score_offset = -3,
						opts = {
							friendly_snippets = true,
							search_paths = { vim.fn.stdpath("config") .. "/snippets" },
							global_snippets = { "all" },
							extended_filetypes = {},
							ignored_filetypes = {},
						},
					},
					buffer = {
						name = "Buffer",
						module = "blink.cmp.sources.buffer",
						fallback_for = { "lsp" },
					},
				},
			},
			trigger = {
				completion = {
					keyword_range = "full", -- full|prefix
				},
			},
			highlight = {
				use_nvim_cmp_as_default = true,
			},
			
		},
	},
```
Thanks!

**Comment by stefanboca** [comment]
You're right, `blink.cmp` currently doesn't have any mechanism for emmiting events like `nvim-cmp` does. Implementation of a similar api is up to @Saghen.

However, for now, I've made a somewhat hacky implementation of the cmp events api that should work with codeium.
Could you try it out and let me know if it works for you? To try it, use this spec for `blink.compat`:
```lua
{
  "saghen/blink.compat",
  version = "event",
  opts = {
    enable_events = true,
  }
}
```

Unrelated, but I noticed you used `impersonate_nvim_cmp = true`, and in opts of the codeium source you have `cache_digraphs_on_start = true`. The former is not needed in your case (codeium registers the source if a config option is set, no lazy registration involved), and the latter is an option specific to `cmp-digraphs`, which is the source used as an example in the readme. You can safely remove these. I'll update the readme to explain this better :)

**Comment by elu00** [comment]
Looks great, thanks so much! Can confirm that everything works happily now with that config.
> 
> Unrelated, but I noticed you used `impersonate_nvim_cmp = true`, and in opts of the codeium source you have `cache_digraphs_on_start = true`. The former is not needed in your case (codeium registers the source if a config option is set, no lazy registration involved), and the latter is an option specific to `cmp-digraphs`, which is the source used as an example in the readme. You can safely remove these. I'll update the readme to explain this better :)

Gotcha, thanks for the catch. I think those were left over from me trying random permutations of configs to see if I could get something to work haha.
Unrelated, but is there any chance you could open up a thread for people to post "known-good" cmp-sources/custom configs? [Catppucin](https://github.com/catppuccin/nvim/discussions/323) does something similar for their plugin, and I think it'd be useful for people to get this plugin up and working.

**Comment by xiaket** [comment]
FWIW, I would like to share my working configuration here (using lazy) and hopefully that will help others:

```
  {
    "saghen/blink.cmp",
    dependencies = {
      { "saghen/blink.compat", opts = { enable_events = true } },
      {
        "Exafunction/codeium.nvim",
        dependencies = {
          "nvim-lua/plenary.nvim",
        },
        opts = {},
      },
    },
    lazy = false,
    version = "v0.*", -- use a release tag to download pre-built binaries

    opts = {
      sources = {
        completion = {
          enabled_providers = { "lsp", "path", "snippets", "buffer", "codeium" },
        },

        providers = {
          codeium = {
            name = "codeium",
            module = "blink.compat.source",
            score_offset = 3,
          },
        },
      },
    },
  },
```

**Comment by partounian** [comment]
Thanks. Tried this and similar for supermaven, sadly couldn't get that to work. I might create a blink-cmp source for it if I really want to move away from nvim-cmp / magazine.

**Comment by stefanboca** [comment]
@partounian what specifically wasn't working for you? I have a suspicion that you're running into issues because the source [provides](https://github.com/supermaven-inc/supermaven-nvim/blob/07d20fce48a5629686aefb0a7cd4b25e33947d50/lua/supermaven-nvim/cmp.lua#L40) a method not currently handled by `blink.compat`, or that it returns '*' as a trigger character (not sure if that's supposed to be a wildcard). I'd be happy to look into seeing if it's possible to get supermaven working if you provide more details. It might also be pretty simple to have supermaven implement a `blink.cmp` source directly (or write a PR to do so), because it looks like the `nvim-cmp` source doesnt contain much business logic itself.

**Comment by partounian** [comment]
Hi @stefanboca,

The issue I observed was Supermaven results didn't populate in blink. Here is the repo where I tried to get blink working https://github.com/partounian/nvim . https://github.com/Allaman/nvim/compare/main...partounian:nvim:main#diff-0617f1c5fc6b1171ec6a84b6a6bc91b68f0d8e091dd563d1507526dda625a172 

I tried with and without `impersonate_nvim_cmp = true` and `enable_events = true`. Tried using `event = "InsertEnter"` instead of `lazy = false`. Tried with and without [supermaven requiring blink as a dependency](https://github.com/Allaman/nvim/compare/main...partounian:nvim:main#diff-f1175ebe1c59346d739f80e124d511aa8ff3fc53e3679f30fcaa1bb09cbd3328) and vice versa. 

Sidenote, @stefanboca do you use any AI code completion tools? If so, I'm curious to know which one you like most

**Comment by stefanboca** [comment]
@partounian That's strange. I'm not really sure what could be causing on blink's side. I wonder if there's an issue with the supermaven plugin? It looks like some people are are having issues with nvim-cmp itself as well (https://github.com/supermaven-inc/supermaven-nvim/issues/118), not sure if that's related. I might take a look into this further at some point.

I don't use any AI code completion tools :)

**Comment by stefanboca** [comment]
@partounian see #14. I believe the issue you were having with supermaven is solved.

**Comment by cxwx** [comment]
not worked now

**Comment by cxwx** [comment]
codeium.nvim has its own module now. great
