### ISSUE TITLE
how to load something like tailwindcss-colorizer-cmp.nvim

### ISSUE THREAD

**Issue by mirsella** [Saghen/blink.compat#4]
hello !

https://github.com/roobert/tailwindcss-colorizer-cmp.nvim

since it has to set its format function

thanks !

**Comment by saghen** [comment]
Tailwind coloring is supported natively in blink with the `reversed` draw mode. Other modes will be supported soon. Supporting nvim-cmp's format function is out of scope

**Comment by mirsella** [comment]
oh sorry for the issue, have a good day !
