### ISSUE TITLE
Get error when using it with Dressing(pcall(require, "cmp"))

### ISSUE THREAD

**Issue by fcying** [Saghen/blink.compat#9]
`dressing.nvim` have this code
https://github.com/stevearc/dressing.nvim/blob/master/lua/dressing/input.lua#L493
```
  -- Configure nvim-cmp if installed
  local has_cmp, cmp = pcall(require, "cmp")
  if has_cmp then
    cmp.setup.buffer({
      enabled = opts.completion ~= nil,
      sources = {
        { name = "omni" },
      },
    })
  end
```

When using `blink.compact`, this code throws an error. Is there any way to work around it?

**Comment by stefanboca** [comment]
The error itself should be simple to fix. I can add a dummy `cmp.setup.buffer` function that does nothing. However, `blink.cmp` does not currently have a way to set a per-buffer configuration, so implementing the functionality of `cmp.setup.buffer` is not feasible. In this case, it looks like `dressing.nvim` is only enabling the `omni` source, so it shouldn't have much impact.

**Comment by fcying** [comment]
it work now, thanks
